apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app }}
    component: registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    {{ .Values.dockerconfigjson }}
