apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repo-helm-app
  namespace: argocd
spec:
  project: demo-project
  source:
    repoURL: "https://github.com/devops-itmo-learn/gitops_manifests.git"
    path: "manifests/helm-chart"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - secrets://values.secret.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-dev

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
