apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-helm-app
  namespace: argocd
spec:
  project: demo-project
  source:
    chart: demo-chart
    repoURL: docker.io/gitopsitmo
    targetRevision: 0.1.0
    helm:
      valueFiles:
      - values.yaml
      - secrets://values.secret.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-dev

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
