apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
    app: {{ .Values.app }}
    component: config
data:
  SERVER_PORT: "{{ .Values.ports.port }}"
  SPRING_APPLICATION_NAME: "{{ .Values.app }}"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_SPRING_WEB: "DEBUG"
