apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "helm-chart.labels" . | nindent 4 }}
    app: {{ .Values.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}
  ports:
    - name: http
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.port }}
      protocol: TCP
      nodePort: {{ .Values.ports.nodePort }}
