dockerconfigjson: ENC[AES256_GCM,data:ZFHEIcLFa/B2lt/NbWxu7Dl/oYM4kcNkLW4oPRroy8+/+0LX1YD6M7K2QQmKKrGJjE5UKTF3urbXoXvI8B2RX3el00kEUQyEaXMf4wdMGgDIVra4T8ox65Jhh0KtopmTTEalpl1er6Zaqn3khhheKouhg9funYpshDucg2txX/+tpfXf+tUR3BSOfG5OHndmTd9uYtmWrkMRXW0mi4P2/P9oKGFCmH+Pv/TpO8YRe1+GRx1naufeYjK2Zqud5IHgsa1+h2QEtT7Uw5VVQbP/3JtTE1n1B/v/1tXE9CnhecsOqsyJqJtTQpb9/gsqHqq4mrpkcGvx93bpVPHgvz2/2nfYNmjk2FnkgcQXxH419MtbZGQQ4y0kA0eMHtB/HeQy4hUHSNrUSdE1rM3F,iv:jxcNGSZUoEp0ryKAj7Sj1A9rhqg69gVKkhAQsfJOvJE=,tag:rUiT5/ZySW+DfMmrDXImdQ==,type:str]
sops:
    age:
        - recipient: age14dgrng5hlddukqlstsvrz263arsxfzmyx37prqe0d0qqxwltx3eqa2pyjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaVRyNWRNQ25pR3hUOWow
            RFZHbHdORjFKOWM0V2UvZytXMjJLWXZjdjNvCnpIM1hOdjFydjB3YThwZ0h2VzVh
            emRGRVFsa0lJV2YrN1hYYy9xTHQ5UjQKLS0tIEZ5TWhLeXk1dEtjMmpMQitNcm9u
            WWlaY0t0MWpQVjNxZVRtWXBFMWhRd1UKcEqYop1uRhuGCpd4wuM/X/O2tfiaLEaR
            l5Zwg4BeWbLTnpaofB38/RkFeuiTFFxr4Nnsf3UI9w6OqgZ3p51wQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T15:46:22Z"
    mac: ENC[AES256_GCM,data:2OkN5GzcVoUDv4IhUMUMTTHiZUrZ1XcqsQ+xOr6bWZqNmUqNIlF5etVVnS4UnJJt7argpiUD9bA7I825fqmOf4RmktRZEkxGDvEhz97gXxclfaocFZzY58r9VxsOSnhcqwmaO+7HvoZoTXX3uYCyWDbeQ9MKTm/ArhIk8sUKY7w=,iv:tG7hGgWX4UDXj/uYa286OI4i+v9aJTgNG5AiWymAEVw=,tag:vMYKoL9yC14nU+eDtht7Zg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
